# This is a basic workflow to help you get started with Actions

name: Covid-19 Tracker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
        
    - name: npm/yarn/pnpm install
      uses: Jaid/action-npm-install@v1.2.4
      with:
        # NODE_ENV setting for installing execution (affects the amount of dependencies installed, but I would recommend keeping development in any case).
        nodeEnv: development
        # Can be "npm", "yarn", "pnpm" or "auto". "auto" will determine the package manager by looking into the repo's files. This is very accurate, so you normally don't want to change this.
        packageManager: auto
        # If true and node_modules folder already exists, this action will be skipped assuming npm install is not required.
        skipIfNodeModulesExists: false
        
        
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        # Yarn command
        cmd: install
        
    - name: creating build
      run: yarn build
        
    
    - name: Install Surge
      run: npm install -g surge 
    - name: Run Surge
      run: surge ./build http://zubair-covid-tracker.surge.sh/ --token ${{secrets.PROJECT001_SURGE_TOKEN}}
